version: '3'
services:
  notebook:
    image: jupyter/base-notebook
    ports:
      - "8888:8888"
    logging:
      driver: awslogs
      options:
        awslogs-group: jupyterhubdemo
        awslogs-region: eu-west-1
        awslogs-stream-prefix: notebook